// <auto-generated />
using System;
using ContestService.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContestService.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250507160831_DataSeed")]
    partial class DataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContestService.DAL.Entities.Jury", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Juries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ea8bf84e-4361-4e4e-be6c-76a0a000895e"),
                            Birthday = new DateOnly(1977, 11, 14),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Hoyt",
                            Surname = "Senger",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("962aafad-3036-42b1-9691-0ea673961986")
                        },
                        new
                        {
                            Id = new Guid("02220676-0775-4f06-9c7b-cb169f443c95"),
                            Birthday = new DateOnly(1983, 3, 29),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Nat",
                            Surname = "Kshlerin",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("38771bdd-42e9-4681-a811-02df65df89f0")
                        },
                        new
                        {
                            Id = new Guid("b0b2a94f-debe-4c15-8fb5-f550b658d611"),
                            Birthday = new DateOnly(2004, 10, 17),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Blanche",
                            Surname = "Yost",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("61268129-382f-4108-ae82-09b09df6c89d")
                        },
                        new
                        {
                            Id = new Guid("f4e0af60-2da2-4862-8d48-01b32063ebc8"),
                            Birthday = new DateOnly(1948, 9, 12),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tiana",
                            Surname = "Stamm",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("4bfd943f-9408-4730-9b4e-8b3e136fa29e")
                        },
                        new
                        {
                            Id = new Guid("96c89650-283b-46ee-8ce1-ddcd72c3fa9f"),
                            Birthday = new DateOnly(1953, 5, 2),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Phyllis",
                            Surname = "Konopelski",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("13048571-68da-4bdc-9b8f-834f760b77a4")
                        });
                });

            modelBuilder.Entity("ContestService.DAL.Entities.MusicalInstrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NominationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NominationId");

                    b.ToTable("MusicalInstruments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dae78225-f9a6-4486-b2bb-2ff7fa3be40e"),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Licensed Concrete Chips",
                            NominationId = new Guid("e2d8a1e7-898f-43cb-a9b8-ec19a97873ad"),
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c42aee05-858a-428c-a5d5-ea4a4ca8b9b4"),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Fantastic Cotton Ball",
                            NominationId = new Guid("e2d8a1e7-898f-43cb-a9b8-ec19a97873ad"),
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f45683b8-a05a-45e8-bb0f-629f0b91aa5e"),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Handmade Soft Computer",
                            NominationId = new Guid("e2d8a1e7-898f-43cb-a9b8-ec19a97873ad"),
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("df7ef85b-7144-46f9-b0d9-5844f070ec78"),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Generic Soft Shirt",
                            NominationId = new Guid("e2d8a1e7-898f-43cb-a9b8-ec19a97873ad"),
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d7cee254-b063-4be1-8611-0973c757f2f3"),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Handmade Frozen Bike",
                            NominationId = new Guid("406f403f-43c8-431f-9351-6fe261036779"),
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d407b303-63c2-4a0e-9ca5-fa853bb1ac2c"),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Licensed Rubber Chair",
                            NominationId = new Guid("406f403f-43c8-431f-9351-6fe261036779"),
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("dea1389c-8dcb-4da2-ad5f-4507173f7705"),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Incredible Cotton Fish",
                            NominationId = new Guid("406f403f-43c8-431f-9351-6fe261036779"),
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9ddf2c9d-8b94-477c-9e51-df5cf9633736"),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Refined Frozen Keyboard",
                            NominationId = new Guid("406f403f-43c8-431f-9351-6fe261036779"),
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("cfb5d935-b0c1-47d3-b806-5fe0117beb9b"),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Licensed Wooden Bacon",
                            NominationId = new Guid("186bbe09-6947-4039-8c6a-0b1fbdd1f985"),
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9acb28bf-4af7-4fc7-96d5-151dd3bb1e73"),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Unbranded Steel Fish",
                            NominationId = new Guid("186bbe09-6947-4039-8c6a-0b1fbdd1f985"),
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5d84636c-1b4f-4d8f-afdf-ae3373810503"),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Handmade Metal Bacon",
                            NominationId = new Guid("186bbe09-6947-4039-8c6a-0b1fbdd1f985"),
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("0eed4b50-d4b9-4fc7-b2ca-6a54c0ec6c1a"),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Refined Frozen Cheese",
                            NominationId = new Guid("186bbe09-6947-4039-8c6a-0b1fbdd1f985"),
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ContestService.DAL.Entities.Nomination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Nominations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e2d8a1e7-898f-43cb-a9b8-ec19a97873ad"),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Funk",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("406f403f-43c8-431f-9351-6fe261036779"),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Classical",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("186bbe09-6947-4039-8c6a-0b1fbdd1f985"),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "World",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ContestService.DAL.Entities.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MusicalInstrumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MusicalInstrumentId");

                    b.ToTable("Participants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3bcdb14d-446d-49c8-8153-91ce0139baaf"),
                            Birthday = new DateOnly(1953, 6, 12),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("dae78225-f9a6-4486-b2bb-2ff7fa3be40e"),
                            Name = "Alexandre",
                            Surname = "Hackett",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("e07e68b4-9c15-4758-884a-93ee2ff7bac1")
                        },
                        new
                        {
                            Id = new Guid("4eeef696-868d-4830-ac86-ff9c2d7de60b"),
                            Birthday = new DateOnly(1969, 2, 23),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("dae78225-f9a6-4486-b2bb-2ff7fa3be40e"),
                            Name = "Marianne",
                            Surname = "Cassin",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("27449ef2-b2b2-4fd3-b349-db5e51d4e232")
                        },
                        new
                        {
                            Id = new Guid("9ea38c43-df14-4cf0-a8d8-717a29fc96f2"),
                            Birthday = new DateOnly(1983, 8, 17),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("dae78225-f9a6-4486-b2bb-2ff7fa3be40e"),
                            Name = "Cristopher",
                            Surname = "Lowe",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("851f6c79-4979-4c2e-87ca-c2daad3483d1")
                        },
                        new
                        {
                            Id = new Guid("b7dc85ba-91fb-4a6c-b4a4-f1050df428fd"),
                            Birthday = new DateOnly(1987, 3, 18),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("dae78225-f9a6-4486-b2bb-2ff7fa3be40e"),
                            Name = "Bartholome",
                            Surname = "Douglas",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("7dd769a6-75ad-4eb3-baa4-9d519398b4cd")
                        },
                        new
                        {
                            Id = new Guid("bb419518-8924-43b7-9738-9f7d9d00d83d"),
                            Birthday = new DateOnly(1983, 12, 2),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("c42aee05-858a-428c-a5d5-ea4a4ca8b9b4"),
                            Name = "Caden",
                            Surname = "Cassin",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("1cc9a40a-ee51-4823-85c4-ca65838a8876")
                        },
                        new
                        {
                            Id = new Guid("edd309c0-2da3-4ecc-9c40-7d2e877aa1a5"),
                            Birthday = new DateOnly(1972, 3, 25),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("c42aee05-858a-428c-a5d5-ea4a4ca8b9b4"),
                            Name = "Kristy",
                            Surname = "Stanton",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("eb62066a-ecb9-4717-9102-6a304b5a966e")
                        },
                        new
                        {
                            Id = new Guid("8fd335ac-4df2-4fe2-8708-f0abbaf47781"),
                            Birthday = new DateOnly(1954, 5, 25),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("c42aee05-858a-428c-a5d5-ea4a4ca8b9b4"),
                            Name = "Walker",
                            Surname = "Lehner",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("f236786b-9fd4-4641-bcaf-d07d66729433")
                        },
                        new
                        {
                            Id = new Guid("b28d0f13-8ece-475b-9bd5-df4fbd6de9f3"),
                            Birthday = new DateOnly(2001, 2, 15),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("c42aee05-858a-428c-a5d5-ea4a4ca8b9b4"),
                            Name = "Makenzie",
                            Surname = "Ruecker",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("ff8b0170-0238-427b-af02-9654ac0ee7b9")
                        },
                        new
                        {
                            Id = new Guid("4d4caffe-587a-4d84-af6f-d2a007c22bbd"),
                            Birthday = new DateOnly(2005, 10, 1),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("f45683b8-a05a-45e8-bb0f-629f0b91aa5e"),
                            Name = "Tierra",
                            Surname = "Stroman",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("84569f0a-1d3d-42e7-8100-e019222c660f")
                        },
                        new
                        {
                            Id = new Guid("e2dc2921-b854-444a-b53d-6082168daf4c"),
                            Birthday = new DateOnly(1950, 9, 30),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("f45683b8-a05a-45e8-bb0f-629f0b91aa5e"),
                            Name = "Davion",
                            Surname = "O'Conner",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("683f7337-eb08-41ee-be5b-ff4715ad4626")
                        },
                        new
                        {
                            Id = new Guid("ec18dbed-ac57-4926-87de-562738c7f792"),
                            Birthday = new DateOnly(1981, 4, 26),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("f45683b8-a05a-45e8-bb0f-629f0b91aa5e"),
                            Name = "Shanny",
                            Surname = "Mosciski",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("8b530981-93b5-4614-acb9-c3d553e06c13")
                        },
                        new
                        {
                            Id = new Guid("d7b14bfc-96a8-41af-b7ba-97e76d06ba3f"),
                            Birthday = new DateOnly(1999, 1, 6),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("f45683b8-a05a-45e8-bb0f-629f0b91aa5e"),
                            Name = "Layne",
                            Surname = "Collier",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("b0e5ab6b-43e2-4d9b-981e-4c844f7c8f93")
                        },
                        new
                        {
                            Id = new Guid("bcd23079-ee8d-4fac-b8e1-3c27ed5b843b"),
                            Birthday = new DateOnly(2005, 12, 6),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("df7ef85b-7144-46f9-b0d9-5844f070ec78"),
                            Name = "Deshaun",
                            Surname = "Corwin",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("a87e6b54-1bd1-4f81-a501-f64002893dc6")
                        },
                        new
                        {
                            Id = new Guid("d598dd06-f8e6-4712-b28e-60a582777cd3"),
                            Birthday = new DateOnly(1956, 10, 4),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("df7ef85b-7144-46f9-b0d9-5844f070ec78"),
                            Name = "Trey",
                            Surname = "Veum",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("5c4c3387-d138-4410-8751-edb357bcc8d1")
                        },
                        new
                        {
                            Id = new Guid("ada7f011-73ed-44f9-8746-a332dc463493"),
                            Birthday = new DateOnly(1986, 7, 30),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("df7ef85b-7144-46f9-b0d9-5844f070ec78"),
                            Name = "Dolores",
                            Surname = "Mertz",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("da97baa7-ad9c-4122-9cd2-cf42db5b646d")
                        },
                        new
                        {
                            Id = new Guid("783be7ab-20f5-4809-a53c-8fd913d1e699"),
                            Birthday = new DateOnly(1970, 4, 8),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("df7ef85b-7144-46f9-b0d9-5844f070ec78"),
                            Name = "Uriah",
                            Surname = "Reinger",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("c28d102b-138f-42ee-820e-61306fa1cbc1")
                        },
                        new
                        {
                            Id = new Guid("812c296a-c2a6-4642-b7bf-4927e2f34632"),
                            Birthday = new DateOnly(1971, 3, 17),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("d7cee254-b063-4be1-8611-0973c757f2f3"),
                            Name = "Don",
                            Surname = "Frami",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("690842af-f16b-4854-82c5-1865725b1362")
                        },
                        new
                        {
                            Id = new Guid("c2cc8d9c-4a9c-4dc4-b8da-f3d92bf17fa3"),
                            Birthday = new DateOnly(1957, 9, 9),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("d7cee254-b063-4be1-8611-0973c757f2f3"),
                            Name = "Domenico",
                            Surname = "D'Amore",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("d8385332-dfd4-4795-84db-f92c2442977a")
                        },
                        new
                        {
                            Id = new Guid("78da0424-a872-44cf-8ae7-bbe15010e2b5"),
                            Birthday = new DateOnly(1973, 2, 12),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("d7cee254-b063-4be1-8611-0973c757f2f3"),
                            Name = "Jamil",
                            Surname = "Jacobs",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("301be1fb-0017-43b2-84af-6318960ebe41")
                        },
                        new
                        {
                            Id = new Guid("f7fcff80-7767-4488-a0fb-3bd3fbed2fba"),
                            Birthday = new DateOnly(1949, 5, 30),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("d7cee254-b063-4be1-8611-0973c757f2f3"),
                            Name = "Josefa",
                            Surname = "O'Keefe",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("17a16040-56b2-4bf8-b269-75c4f54ac60c")
                        },
                        new
                        {
                            Id = new Guid("632ccaf0-a404-4450-b04f-21293979e9cb"),
                            Birthday = new DateOnly(1987, 7, 20),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("d407b303-63c2-4a0e-9ca5-fa853bb1ac2c"),
                            Name = "Ellsworth",
                            Surname = "Willms",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("a6f1cbf1-4cb0-42d3-b80f-0bdcd65807c7")
                        },
                        new
                        {
                            Id = new Guid("4884b967-ff70-43b4-a186-628f1c052617"),
                            Birthday = new DateOnly(1982, 3, 18),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("d407b303-63c2-4a0e-9ca5-fa853bb1ac2c"),
                            Name = "Oral",
                            Surname = "Stark",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("640ace8d-3f84-45e3-b73f-b8f0576372b1")
                        },
                        new
                        {
                            Id = new Guid("f2333bdf-7e4d-400a-8420-2f16336880ef"),
                            Birthday = new DateOnly(1989, 12, 22),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("d407b303-63c2-4a0e-9ca5-fa853bb1ac2c"),
                            Name = "Claudine",
                            Surname = "Waters",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("f33a0b60-2f88-4356-a545-911b58535f20")
                        },
                        new
                        {
                            Id = new Guid("a7689877-2ce6-4331-91ee-e83ba6ddfcdd"),
                            Birthday = new DateOnly(1995, 3, 8),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("d407b303-63c2-4a0e-9ca5-fa853bb1ac2c"),
                            Name = "Jewel",
                            Surname = "Larkin",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("5d6f8826-26ca-47fc-ba6d-aff1a82eb597")
                        },
                        new
                        {
                            Id = new Guid("f29a1317-f44f-4b3e-b7a5-4c5d2f5a7b79"),
                            Birthday = new DateOnly(1948, 6, 13),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("dea1389c-8dcb-4da2-ad5f-4507173f7705"),
                            Name = "Akeem",
                            Surname = "Lowe",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("d6d605e8-1e7c-424c-909c-d9a58bd9cb3b")
                        },
                        new
                        {
                            Id = new Guid("4257a716-ee8a-41a5-a610-d50d22d3f94c"),
                            Birthday = new DateOnly(1951, 4, 24),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("dea1389c-8dcb-4da2-ad5f-4507173f7705"),
                            Name = "Baron",
                            Surname = "Stamm",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("619769e4-a332-4d48-a461-884487b66682")
                        },
                        new
                        {
                            Id = new Guid("2dde21b5-669e-4f10-b0f5-a0f7a737db44"),
                            Birthday = new DateOnly(1975, 6, 8),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("dea1389c-8dcb-4da2-ad5f-4507173f7705"),
                            Name = "Audie",
                            Surname = "Armstrong",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("b50149cb-666d-4fc7-b864-2196a8e9b142")
                        },
                        new
                        {
                            Id = new Guid("25137d6c-c912-43d9-9495-b61f0777e1da"),
                            Birthday = new DateOnly(1949, 1, 12),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("dea1389c-8dcb-4da2-ad5f-4507173f7705"),
                            Name = "Mitchell",
                            Surname = "Ledner",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("b3f654f5-d622-415f-801b-501c58a11cf9")
                        },
                        new
                        {
                            Id = new Guid("d68c716f-f3ab-492d-92fd-ae48a8bdea48"),
                            Birthday = new DateOnly(1959, 12, 30),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("9ddf2c9d-8b94-477c-9e51-df5cf9633736"),
                            Name = "Jeffry",
                            Surname = "Prohaska",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("5c953f57-e8df-4e2d-9587-d5e19d8ad4fa")
                        },
                        new
                        {
                            Id = new Guid("6598db7b-e9be-4af8-a900-3ce6339244a5"),
                            Birthday = new DateOnly(1966, 2, 7),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("9ddf2c9d-8b94-477c-9e51-df5cf9633736"),
                            Name = "Nikko",
                            Surname = "Gerlach",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("73fa0e6b-b8b7-4c47-a1c2-8f68b98b0608")
                        },
                        new
                        {
                            Id = new Guid("431be4ba-d3e1-4d8a-ba34-5cc2ec075a08"),
                            Birthday = new DateOnly(1964, 2, 27),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("9ddf2c9d-8b94-477c-9e51-df5cf9633736"),
                            Name = "Delmer",
                            Surname = "Kilback",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("94d63026-e2a7-4581-a01b-d25d412c2610")
                        },
                        new
                        {
                            Id = new Guid("695fe4ac-9217-4958-b829-82c2649616ff"),
                            Birthday = new DateOnly(1991, 4, 18),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("9ddf2c9d-8b94-477c-9e51-df5cf9633736"),
                            Name = "Wilford",
                            Surname = "Bartell",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("386ede6f-14a5-4c94-9657-51d3fda7615b")
                        },
                        new
                        {
                            Id = new Guid("331d287f-18e0-402a-9824-60689a1a41d9"),
                            Birthday = new DateOnly(1956, 8, 22),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("cfb5d935-b0c1-47d3-b806-5fe0117beb9b"),
                            Name = "Davon",
                            Surname = "Torphy",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("78fb34b2-e597-411e-9b8e-3dd4d00f4855")
                        },
                        new
                        {
                            Id = new Guid("a0ab413c-17f6-468f-8fd4-053d8092a1c1"),
                            Birthday = new DateOnly(1996, 2, 27),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("cfb5d935-b0c1-47d3-b806-5fe0117beb9b"),
                            Name = "Harold",
                            Surname = "Champlin",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("b35abd54-4eaf-4777-834e-daaa4f834e82")
                        },
                        new
                        {
                            Id = new Guid("94416735-6ae4-4786-a8cf-722de3a8972b"),
                            Birthday = new DateOnly(1969, 7, 16),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("cfb5d935-b0c1-47d3-b806-5fe0117beb9b"),
                            Name = "Nyasia",
                            Surname = "Herzog",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("dacffa47-e02a-4198-b2fe-3ddef38fb30b")
                        },
                        new
                        {
                            Id = new Guid("0df7992c-df4f-4bdb-bfbd-6f520d77c095"),
                            Birthday = new DateOnly(1948, 12, 5),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("cfb5d935-b0c1-47d3-b806-5fe0117beb9b"),
                            Name = "Nicklaus",
                            Surname = "Okuneva",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("36dc9934-c664-4b18-b4be-31773974059d")
                        },
                        new
                        {
                            Id = new Guid("9528b056-3672-4a55-a701-c7b55b0bc4d4"),
                            Birthday = new DateOnly(1982, 8, 25),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("9acb28bf-4af7-4fc7-96d5-151dd3bb1e73"),
                            Name = "Bria",
                            Surname = "Parker",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("e2c8cb3b-705f-4dc2-8a43-4960068f5af7")
                        },
                        new
                        {
                            Id = new Guid("3414d950-900b-4983-bc3d-b9615420986b"),
                            Birthday = new DateOnly(1993, 7, 1),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("9acb28bf-4af7-4fc7-96d5-151dd3bb1e73"),
                            Name = "Aimee",
                            Surname = "Volkman",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("0938fc27-766c-42ea-9d7b-3e60aeb13e07")
                        },
                        new
                        {
                            Id = new Guid("6293af47-5db6-4f5e-bc37-e9c7c8c94fa9"),
                            Birthday = new DateOnly(1991, 7, 11),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("9acb28bf-4af7-4fc7-96d5-151dd3bb1e73"),
                            Name = "Javon",
                            Surname = "Schinner",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("9cdfd514-ed1e-48c2-bbc7-03a88b1aef46")
                        },
                        new
                        {
                            Id = new Guid("f78c715b-4e34-4f8a-9b00-a9fa47b03bb3"),
                            Birthday = new DateOnly(1984, 1, 2),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("9acb28bf-4af7-4fc7-96d5-151dd3bb1e73"),
                            Name = "Jannie",
                            Surname = "Carroll",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("ce55d2b4-7de7-4183-96e3-a9c27b4daefc")
                        },
                        new
                        {
                            Id = new Guid("76fb0351-325a-4d02-afc1-9eb119da8277"),
                            Birthday = new DateOnly(1956, 11, 2),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("5d84636c-1b4f-4d8f-afdf-ae3373810503"),
                            Name = "Emery",
                            Surname = "Doyle",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("8d1f5001-bc15-4143-b58a-a2bd679a6928")
                        },
                        new
                        {
                            Id = new Guid("2fce6fae-2636-45e1-a689-78fb77036410"),
                            Birthday = new DateOnly(1996, 11, 3),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("5d84636c-1b4f-4d8f-afdf-ae3373810503"),
                            Name = "Jaren",
                            Surname = "Howell",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("da16e1f3-a7e1-44e4-a8d9-eee430cb98b2")
                        },
                        new
                        {
                            Id = new Guid("491f9756-e426-4ee6-8704-b68992711ecc"),
                            Birthday = new DateOnly(1990, 1, 17),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("5d84636c-1b4f-4d8f-afdf-ae3373810503"),
                            Name = "Jordy",
                            Surname = "Jakubowski",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("fee50472-e3ca-4c6e-b34f-54c9f40cb8fb")
                        },
                        new
                        {
                            Id = new Guid("c3331c28-c953-4f20-acfe-e3d1cde53041"),
                            Birthday = new DateOnly(1959, 11, 6),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("5d84636c-1b4f-4d8f-afdf-ae3373810503"),
                            Name = "Gilbert",
                            Surname = "Gleason",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("3b5542dc-456f-4544-ae68-53dc7ab0154c")
                        },
                        new
                        {
                            Id = new Guid("ff040c21-1991-4e7b-ac1f-46d57c4c8e2b"),
                            Birthday = new DateOnly(1980, 12, 10),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("0eed4b50-d4b9-4fc7-b2ca-6a54c0ec6c1a"),
                            Name = "Annamae",
                            Surname = "Conroy",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("c638533c-658e-4ee6-901f-681c969cb987")
                        },
                        new
                        {
                            Id = new Guid("fea2754f-3a33-4400-a52f-03733fd1aba2"),
                            Birthday = new DateOnly(1978, 6, 6),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("0eed4b50-d4b9-4fc7-b2ca-6a54c0ec6c1a"),
                            Name = "Emanuel",
                            Surname = "Casper",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("3bf9e07f-9e55-4d7e-a3c4-c00aa19834a0")
                        },
                        new
                        {
                            Id = new Guid("fd03766e-4c99-4b4f-9bb6-1a0e6d10ee67"),
                            Birthday = new DateOnly(1996, 5, 8),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("0eed4b50-d4b9-4fc7-b2ca-6a54c0ec6c1a"),
                            Name = "Sunny",
                            Surname = "Jones",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("7350bbed-7547-4e68-adf7-cf44ebddddee")
                        },
                        new
                        {
                            Id = new Guid("ae6fdc6c-9635-429a-94ab-1e6a0c89e4a8"),
                            Birthday = new DateOnly(1971, 5, 1),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            MusicalInstrumentId = new Guid("0eed4b50-d4b9-4fc7-b2ca-6a54c0ec6c1a"),
                            Name = "Estevan",
                            Surname = "Armstrong",
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("3c5b792e-241f-47c1-ae19-ea2814659112")
                        });
                });

            modelBuilder.Entity("ContestService.DAL.Entities.Stage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Stages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3a9758e-78fc-407f-a447-0e00f3485337"),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2025, 4, 27, 1, 4, 38, 986, DateTimeKind.Utc).AddTicks(9177),
                            Name = "porro",
                            StartDate = new DateTime(2025, 4, 25, 1, 4, 38, 986, DateTimeKind.Utc).AddTicks(9177),
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7af049ce-91cf-4472-9eab-3d2e1105b198"),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2025, 4, 29, 1, 6, 25, 707, DateTimeKind.Utc).AddTicks(1947),
                            Name = "quis",
                            StartDate = new DateTime(2025, 4, 28, 1, 6, 25, 707, DateTimeKind.Utc).AddTicks(1947),
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a5dab53b-d136-4317-95cc-1038b89dd18e"),
                            CreatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2025, 5, 6, 13, 34, 15, 668, DateTimeKind.Utc).AddTicks(6994),
                            Name = "distinctio",
                            StartDate = new DateTime(2025, 5, 4, 13, 34, 15, 668, DateTimeKind.Utc).AddTicks(6994),
                            UpdatedAt = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ContestService.DAL.Entities.MusicalInstrument", b =>
                {
                    b.HasOne("ContestService.DAL.Entities.Nomination", "Nomination")
                        .WithMany("Instruments")
                        .HasForeignKey("NominationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nomination");
                });

            modelBuilder.Entity("ContestService.DAL.Entities.Participant", b =>
                {
                    b.HasOne("ContestService.DAL.Entities.MusicalInstrument", "MusicalInstrument")
                        .WithMany()
                        .HasForeignKey("MusicalInstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicalInstrument");
                });

            modelBuilder.Entity("ContestService.DAL.Entities.Nomination", b =>
                {
                    b.Navigation("Instruments");
                });
#pragma warning restore 612, 618
        }
    }
}
