name: .NET with SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./Contest.Service/Contest.Service.sln

    - name: Build
      run: dotnet build ./Contest.Service/Contest.Service.sln --no-restore --configuration Release

  analyze:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Sonar Scan
      uses: highbyte/sonarscan-dotnet@v2.3.0
      with:
        sonarProjectKey: ${{ vars.SONARPROJECTKEY }}
        sonarProjectName: ${{ vars.SONARPROJECTNAME }}
        sonarOrganization: ${{ vars.SONARORGANIZATION }}
        dotnetBuildArguments: ./Contest.Service/Contest.Service --configuration Release

    env: 
        EXCLUDE_FROM_COVERAGE: "**/Program.cs, **/Extensions/*, **/Exceptions/**, **/Context/*, **/Migrations/*, **/DI/*, **/Entities/*, **/Validators/*, **/Enums/**/*, **/Repositories/**, **/MappingConfigurations/*, **/ViewModels/**/*, **/Controllers/*, **/Utilities/**, **/EventBus/**"
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        EXCLUDE_FROM_SONAR: "**/Migrations/*, **/Dockerfile"